delete from ligne; 
delete from arret; 
insert into ligne (num_ligne) values('1'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '2', 'Antigone'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '4', 'Chateau D o'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '5', 'Comedie'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '6', 'Corum T1'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '7', 'Euromedecine'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '9', 'Halles Paillade'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '10', 'Hauts De Massane'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '11', 'Hop. Lapeyronie'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '12', 'Hotel De Ville'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '13', 'Leon Blum'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '15', 'Malbosc'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '17', 'Mosson'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '19', 'Occitanie'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '22', 'Pl. De L europ'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '26', 'Saint Eloi'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '27', 'Saint Paul'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '28', 'Universites'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '8', 'Gare St-roch T1'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '25', 'Rives Du Lez T1'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '24', 'Port Marianne'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '23', 'Place De France'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '20', 'Odysseum'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '18', 'Moulares'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '16', 'Millenaire'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '918', 'Mondial 98'); 
insert into ligne (num_ligne) values('2'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '30', 'Aiguelongue'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '31', 'Aube Rouge'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '32', 'Beaux Arts'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '33', 'Centurions'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '34', 'Ch. De Gaulle'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '35', 'Clairval'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '36', 'Corum T2'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '37', 'Croix D argent'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '39', 'Georges Pomp<option>ou'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '40', 'Jacou'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '42', 'La Galine'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '45', 'Mail Des Abbes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '46', 'Mas Drevon'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '47', 'Nd Sablassou'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '50', 'Place Carnot'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '54', 'Sabines'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '56', 'Saint Lazare'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '59', 'Via Domitia'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '61', 'Vil. D angoule'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '62', 'Voltaire'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '55', 'Saint Cleophas'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '53', 'Rondelet'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '52', 'Rives Du Lez T2'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '51', 'Pompignane'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '49', 'Pl. De L europ'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '48', 'Nouveau St Roch'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '44', 'Les Aubes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '43', 'Lemasson'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '38', 'Gare St-roch T2'); 
insert into ligne (num_ligne) values('5'); 
insert into arret (num_ligne, id_arret, nom_arret) values('5', '63', 'A. L. Jussieu'); 
insert into arret (num_ligne, id_arret, nom_arret) values('5', '64', 'Aiguelongue'); 
insert into arret (num_ligne, id_arret, nom_arret) values('5', '65', 'Aiguelongue Juss'); 
insert into arret (num_ligne, id_arret, nom_arret) values('5', '66', 'Alpilles'); 
insert into arret (num_ligne, id_arret, nom_arret) values('5', '67', 'Boutonnet'); 
insert into arret (num_ligne, id_arret, nom_arret) values('5', '68', 'Chantecler'); 
insert into arret (num_ligne, id_arret, nom_arret) values('5', '69', 'Clolus'); 
insert into arret (num_ligne, id_arret, nom_arret) values('5', '70', 'Colonel Marchand'); 
insert into arret (num_ligne, id_arret, nom_arret) values('5', '71', 'Marie Caizergues'); 
insert into arret (num_ligne, id_arret, nom_arret) values('5', '72', 'Moulin Gasconnet'); 
insert into arret (num_ligne, id_arret, nom_arret) values('5', '73', 'Nazareth'); 
insert into arret (num_ligne, id_arret, nom_arret) values('5', '74', 'Pierre Rouge'); 
insert into arret (num_ligne, id_arret, nom_arret) values('5', '75', 'Pioch Boutonnet'); 
insert into arret (num_ligne, id_arret, nom_arret) values('5', '76', 'Rene Bougnol'); 
insert into arret (num_ligne, id_arret, nom_arret) values('5', '77', 'Sainte Odile'); 
insert into ligne (num_ligne) values('6'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '79', 'Arceaux'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '80', 'Av. Agriculture'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '81', 'Av. De Toulouse'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '82', 'Av. Des Moulins'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '83', 'Belvedere'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '84', 'Berthelot'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '85', 'Camperiols'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '86', 'Comedie'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '87', 'Ecole Commerce'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '88', 'Erables'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '89', 'Esperance'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '90', 'Estanove'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '91', 'Font Couverte'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '92', 'G. Janvier'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '93', 'Gare Saint-roch'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '94', 'Georges Brassens'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '95', 'Glycines'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '97', 'Las Cazes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '98', 'Las Sorbes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '99', 'Le Grand M'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '100', 'Les Hirondelles'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '101', 'Louvain'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '102', 'Lycee Clemenceau'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '103', 'Lycee J. Monnet'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '104', 'Observatoire'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '105', 'Paladilhe'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '106', 'Parc Malbosc'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '107', 'Pas Du Loup'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '108', 'Paul Bringuier'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '109', 'Paul Rimbaud'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '110', 'Pergola'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '111', 'Peyrou'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '112', 'Pitot'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '113', 'Place Du 8 Mai'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '114', 'Prof. J. Blayac'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '115', 'Ronceray'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '116', 'Rondelet'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '117', 'Saint Clement'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '118', 'Saint Denis'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '119', 'Saint Gabriel'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '120', 'Saint Guilhem'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '121', 'Vega'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '919', 'Gare Saint Roch'); 
insert into ligne (num_ligne) values('7'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '123', 'Berthelot'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '124', 'Cervantes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '125', 'Chateau D o'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '126', 'Cite Roger'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '127', 'Comedie'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '129', 'Crx Du Capitaine'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '130', 'Doria'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '131', 'Etoile'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '132', 'Figairasse'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '133', 'Font Trouve'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '134', 'Francois Dezeuze'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '135', 'Gardioles'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '136', 'Gare Saint-roch'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '137', 'Gouara'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '140', 'H.du Departement'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '143', 'La Pile'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '144', 'La Source'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '145', 'Lepic'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '146', 'Les Bouisses'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '147', 'Lycee Clemenceau'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '148', 'Lycee J. Ferry'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '149', 'Lycee J. Monnet'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '150', 'Maison Sports'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '151', 'Martelliere'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '152', 'Mas De Merle'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '153', 'Metairie Oiseau'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '155', 'Muriers'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '156', 'Myrtes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '157', 'Observatoire'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '158', 'Ormeaux'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '159', 'Peyrou'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '160', 'Pitot'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '161', 'Pleiade'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '162', 'Pous De La Sers'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '163', 'Rondelet'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '164', 'Saint Denis'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '165', 'Saint Guilhem'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '166', 'Saint Jaumes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '167', 'Saint Roch'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '168', 'Sophie Germain'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '920', 'Gare Saint Roch'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '128', 'Croix Rosiers'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '138', 'Grezes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '139', 'Gustave Eiffel'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '142', 'La Martelle'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '154', 'Monsieur Teste'); 
insert into ligne (num_ligne) values('8'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '169', 'Chambery'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '170', 'Cite Mion'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '171', 'Col. Aiguerelles'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '172', 'Frederic Bazille'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '173', 'Gare Routiere'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '174', 'Gare Saint-roch'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '175', 'Helios'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '176', 'Henri Rene'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '177', 'Jean Mirailhet'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '178', 'La Rauze'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '179', 'Les Cedres'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '180', 'Place Carnot'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '181', 'Place Strasbourg'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '182', 'Saint Hilaire'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '183', 'Soleiado'); 
insert into ligne (num_ligne) values('9'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '184', 'Albert Einstein'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '185', 'Alfred Nobel'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '186', 'Andre Malraux'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '187', 'Cim. St Etienne'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '188', 'Cinq Chalets'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '189', 'Colverts'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '190', 'Eureka'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '191', 'Evariste Gallois'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '192', 'Fr. Couperin'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '193', 'G. Marconi'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '194', 'Georges Melies'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '195', 'Grammont'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '196', 'Louis Lepine'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '197', 'Marie Durand'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '198', 'Odysseum'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '199', 'Paul Painleve'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '200', 'Pinville'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '201', 'Pl. De L europ'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '202', 'Pompignag Semard'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '203', 'Saint Jean'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '204', 'Saint Michel'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '205', 'Samuel Morse'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '206', 'Vieille Poste'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '207', 'Volta Fizeau'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '208', 'Zenith'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '922', 'Apollo'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '923', 'Dom. Pompignane'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '924', 'Pierre Laroque'); 
insert into ligne (num_ligne) values('10'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '227', 'Les Bouisses'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '228', 'Les Lacs'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '243', 'Pierre Laroque'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '251', 'Saint Eloi'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '250', 'Saint Cleophas'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '249', 'Sabines'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '248', 'Rouget De Lisle'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '247', 'Roqueturiere'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '246', 'Rieges'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '229', 'Les Pins'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '230', 'Louis Ravas'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '231', 'Lycee J. Ferry'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '232', 'M. Chevalier'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '233', 'Major Flandre'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '234', 'Martelliere'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '235', 'Mas De Bagneres'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '236', 'Millenaire'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '237', 'Odysseum'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '238', 'Ormeaux'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '239', 'Parc Lironde'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '240', 'Passerines'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '241', 'Pastourelles'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '909', 'Patrice Lumumba'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '242', 'Paul Fajon'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '222', 'Henri Dunant'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '223', 'Henri Mares'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '908', 'Jasse De Maurin'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '224', 'Jean Calvin'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '225', 'Lagoya'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '226', 'Le Grand M'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '214', 'Castelle'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '215', 'Ch. De Gaulle'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '216', 'Cheng-du'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '217', 'Cinsaults'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '218', 'Demeter'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '907', 'Ettore Bugatti'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '219', 'Fac De Pharmacie'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '220', 'Garosud'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '221', 'Goelands'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '245', 'Pompignag Semard'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '244', 'Pinville'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '261', 'Yves Du Manoir'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '260', 'Voie Domitienne'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '259', 'Vauguieres'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '258', 'Tourterelles'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '257', 'Tonnelles'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '256', 'Tam'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '255', 'Sophie Germain'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '254', 'Salaison'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '253', 'Sainte Catherine'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '252', 'Saint Lazare'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '210', 'Aiguelongue'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '211', 'Belvedere'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '212', 'Bengalis'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '213', 'Bugarel'); 
insert into ligne (num_ligne) values('11'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '262', 'Anatole France'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '263', 'Bagatelle'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '264', 'Chasseurs'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '265', 'Cheng-du'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '266', 'Cite Gely'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '267', 'Cite Valette'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '268', 'Claret'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '269', 'College Pagnol'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '270', 'Comedie'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '271', 'Craponne'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '272', 'Figuerolles'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '273', 'Gambetta'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '274', 'Gare Saint-roch'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '275', 'Les Bouisses'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '276', 'Les Roses'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '277', 'Pas Du Loup'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '278', 'Paul Fajon'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '279', 'Plan Cabanes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '280', 'Renouvier'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '281', 'Rouget De Lisle'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '282', 'Saint Denis'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '911', 'Saint Guilhem'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '910', 'Observatoire'); 
insert into ligne (num_ligne) values('12'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '283', 'Bellevue'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '284', 'Centrayrargues'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '285', 'Coquelicots'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '286', 'Descartes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '287', 'Frederic Peysson'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '288', 'Gare Routiere'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '289', 'Gare Saint-roch'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '290', 'Henri Rene'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '293', 'Leon Cordes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '295', 'Paquerettes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '296', 'Place Carnot'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '297', 'Place Strasbourg'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '298', 'Porto'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '299', 'Primeveres'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '300', 'Razeteurs'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '301', 'Saint Martin'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '294', 'Marechal Leclerc'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '292', 'La Creche'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '291', 'Jean Vachet'); 
insert into ligne (num_ligne) values('13'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '302', 'Agropolis'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '303', 'Campus Agropolis'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '304', 'E. Architecture'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '305', 'Ecossais'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '306', 'Eugene Bataillon'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '307', 'Fac De Lettres'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '308', 'Gascogne'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '309', 'Henri Dunant'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '310', 'Hortus'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '311', 'Lavalette'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '312', 'Lycee F. Bazille'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '313', 'Maurice Chauvet'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '314', 'Pic St Loup'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '315', 'Plan 4 Seigneurs'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '316', 'Saint Eloi'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '317', 'Universites'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '318', 'Vert Bois'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '319', 'Zoo'); 
insert into ligne (num_ligne) values('14'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '320', 'Andre Malraux'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '321', 'Bd Des Sports'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '322', 'Ernest Renan'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '323', 'Estragon'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '324', 'Foyer Des Aubes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '325', 'Francoise'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '326', 'Jean Mermoz'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '327', 'Leon Blum'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '328', 'Les Aubes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '329', 'Marie Durand'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '330', 'Palombes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '331', 'Pinsons'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '332', 'Pompignag Semard'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '333', 'Saint Maur'); 
insert into ligne (num_ligne) values('15'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '334', 'Anatole France'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '335', 'Carriera'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '336', 'Cite Des Cadres'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '337', 'Comedie'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '338', 'Comte De Nice'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '339', 'Comte Toulouse'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '340', 'Corse'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '341', 'Coubertin'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '342', 'Craponne'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '343', 'Europe'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '344', 'Figuerolles'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '345', 'G. De Nogaret'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '346', 'Gambetta'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '347', 'Gare Saint-roch'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '348', 'Gemeaux'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '349', 'Halles Paillade'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '350', 'Hauts De Massane'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '351', 'Jacques Prevert'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '352', 'La Fontaine'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '353', 'Lausanne'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '354', 'Liberte'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '355', 'Louisville'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '356', 'Lycee J. Guesde'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '357', 'Marie Curie'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '358', 'Mas De Bellevue'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '359', 'Massena'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '360', 'Mosson'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '361', 'Oxford'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '362', 'Petit Bard'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '363', 'Pierre Cardenal'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '364', 'Pl. D italie'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '365', 'Plan Cabanes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '366', 'Prof. Forgues'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '367', 'Raimbaud orang'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '368', 'Renaudel'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '369', 'Renouvier'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '370', 'Route De Lodeve'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '371', 'Saint Denis'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '372', 'Tonnelles'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '373', 'Tr<option>ent'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '913', 'Saint Guilhem'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '912', 'Observatoire'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '921', 'Gare Saint Roch'); 
insert into ligne (num_ligne) values('16'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '374', 'Alco'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '375', 'Ambroise Pare'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '376', 'Antennes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '377', 'Apothicaires'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '378', 'Appel Du 18 Juin'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '379', 'Arceaux'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '380', 'Cevennes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '381', 'Chateau D o'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '382', 'Cite De L arme'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '383', 'Cite Mion'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '384', 'Coll. C. Claudel'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '386', 'Doria'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '387', 'Euromedecine'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '388', 'Fr. Fabreges'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '389', 'Frederic Bazille'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '390', 'Garcia Lorca'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '391', 'Gare Routiere'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '392', 'Gare Saint-roch'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '393', 'Henri Rene'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '394', 'Industrie'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '395', 'Iris'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '397', 'La Gaillarde'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '398', 'Las Rebes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '399', 'Louis Ravas'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '400', 'Lucullus'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '401', 'Marche Gare'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '402', 'Mas Argelliers'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '403', 'Mas St Pierre'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '404', 'Observatoire'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '405', 'Occitanie'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '406', 'Peyrou'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '407', 'Pierre Viala'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '408', 'Pitot'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '409', 'Place Carnot'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '410', 'Place Strasbourg'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '411', 'Puech Villa'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '412', 'Rte De Ganges'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '413', 'Saint Guilhem'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '414', 'Saint Priest'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '415', 'Sainte Genevieve'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '416', 'Sainte Therese'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '417', 'Saporta'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '418', 'Tournezy'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '419', 'Val D aurelle'); 
insert into ligne (num_ligne) values('44'); 
insert into arret (num_ligne, id_arret, nom_arret) values('44', '935', 'Boutonnet'); 
insert into arret (num_ligne, id_arret, nom_arret) values('44', '934', 'Albert 1er'); 
insert into arret (num_ligne, id_arret, nom_arret) values('44', '939', 'Saint Eloi'); 
insert into arret (num_ligne, id_arret, nom_arret) values('44', '938', 'Philipp<option>es'); 
insert into arret (num_ligne, id_arret, nom_arret) values('44', '937', 'Louis Blanc'); 
insert into arret (num_ligne, id_arret, nom_arret) values('44', '936', 'Corum'); 
insert into ligne (num_ligne) values('45'); 
insert into arret (num_ligne, id_arret, nom_arret) values('45', '933', 'Victoire'); 
insert into arret (num_ligne, id_arret, nom_arret) values('45', '932', 'St Jean Le Sec'); 
insert into arret (num_ligne, id_arret, nom_arret) values('45', '931', 'St Jean Centre'); 
insert into arret (num_ligne, id_arret, nom_arret) values('45', '930', 'Sabines'); 
insert into arret (num_ligne, id_arret, nom_arret) values('45', '929', 'C. Commercial'); 
